### ISSUE TITLE
SyntaxError: Invalid regular expression: /^\tts\(?:([^\/]+?))\/?$/: Unmatched ')'

### ISSUE THREAD

**Issue by BrayanMnz** [fonoster/fonoster#169]
**Describe the bug**

The bug is a path not normalized to work properly on Windows OS. 

Is located on **_\node_modules\@fonos\voice\dist\server.js:38:13)_**

**To Reproduce**

To reproduce the behavior just run the Voice Server script on a Windows Machine and it will raise a Syntax Error.

1. Go to 'git bash, cmd or PowerShell'
2. Type 'node index.js on Project Directory'
3. Then, 'Syntax Error is Raised'

**Expected behavior**
The Voice Server needs to run properly here without any problem on any OS.

**Screenshots**
![image](https://user-images.githubusercontent.com/61812255/135933519-d15c6fa2-e84a-45cf-94e3-ce9954020f96.png)

**System information (please complete the following):**
  
    -  OS: Windows 10
    -     NodeJS, NPM versions [e.g. v14.17.4, 6.14.14]
    -     CTL version [e.g. 0.1 ]

**Additional context**

`SyntaxError: Invalid regular expression: /^\tts\(?:([^\/]+?))\/?$/: Unmatched ')'
    at new RegExp (<anonymous>)
    at pathtoRegexp (C:\Users\Braya\OneDrive\Escritorio\Workspace\voiceapp\node_modules\path-to-regexp\index.js:128:10)
    at new Layer (C:\Users\Braya\OneDrive\Escritorio\Workspace\voiceapp\node_modules\express\lib\router\layer.js:45:17)
    at Function.route (C:\Users\Braya\OneDrive\Escritorio\Workspace\voiceapp\node_modules\express\lib\router\index.js:494:15)
    at Function.app.<computed> [as get] (C:\Users\Braya\OneDrive\Escritorio\Workspace\voiceapp\node_modules\express\lib\application.js:481:30)
    at VoiceServer.listen (C:\Users\Braya\OneDrive\Escritorio\Workspace\voiceapp\node_modules\@fonos\voice\dist\server.js:38:13)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)`

**Comment by psanders** [comment]
Thanks for the detailed report. This is clearly a bug. I will be looking into this soon.

**Comment by psanders** [comment]
I push a patch to solve this. Can you confirm it works properly with `0.1.27`?

**Comment by BrayanMnz** [comment]
Bug fixed with `0.1.27` version. 
Confirmed on the same environment where it was thrown.

Can be closed.

**Comment by psanders** [comment]
Great! Thanks.
